name: Delete Merged branch on release
on:
  release:
    types: [published]
  
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:

      - name: Delete Manually
        run: |
          git fetch
          git branch
          git branch --merged main | grep -v "^\* main" | xargs -n 1 -r git branch -d
          git branch

      #- name: delete branch
      #  uses: SvanBoxel/delete-merged-branch@main
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Delete branches again
      #  uses: zjutszl/delete-merged-branch-asdf@master

      #- name: Delete merged branch
      #  uses: koj-co/delete-merged-action@master
      #  with:
      #    branches: "!master, !production, !main, *"
      #  env:
      #    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      #- name: Checkout repository
      #  uses: actions/checkout@v2
      
      #- name: Run delete-old-branches-action
      #  uses: beatlabs/delete-old-branches-action@v0.0.9
      #  with:
      #    repo_token: ${{ github.token }}
      #    date: '2 minutes ago'
      #    dry_run: true
      #    delete_tags: true
      #    minimum_tags: 5
      #    extra_protected_branch_regex: ^(foo|bar)$
      #    extra_protected_tag_regex: '^v.*'
      #    exclude_open_pr_branches: true

