name: Filter-Env

on: workflow_dispatch

permissions:
  contents: read
  actions: read
  pull-requests: write
  checks: write

defaults:
  run:
    shell: powershell

env:
  workflowDepth: 1

jobs:
  job1:
    runs-on: [ windows-latest ]
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1  
        run: echo "test=hello" >> $GITHUB_OUTPUT
        shell: bash
  job2:
    runs-on: [ windows-latest ]
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1 $OUTPUT2"
