name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      all-environments:
        type: boolean
        description: Deploy both Dev & QAT
      name:
        type: choice
        description: Run tests
        options: 
        - No
        - Yes

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ fromJSON('["", ""]')[github.event.inputs.all-environments == 'true'] }} ${{ github.event.inputs.name }}"
