name: 'Matrix 3'

on: workflow_dispatch

jobs:
  Matrix:
    strategy: 
      matrix:
        include: [{"environment":"CORE_DEV (DEV)","os":"windows-latest"},{"environment":"CORE_QA (QA)","os":"windows-latest"}]
    runs-on: ${{matrix.os}}
    name: Deploy to ${{ matrix.environment }}
    steps:
      - name: Checkout
        run: echo "Hello world"
