name: 'onMerge'

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["Pull Request Handler"]
    types:
      - completed
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/*.yaml'
      - '!.github/workflows/CICD.yaml'
      - '!.github/workflows/CICD_v2.yaml'
      - '!.github/workflows/CICD_QA.yaml'
    branches: [ 'main', 'release/*', 'feature/*' ]

run-name: ${{ fromJson(format('["","Check pull request from {1}/{2}{0} {3}"]',':',github.event.workflow_run.head_repository.owner.login,github.event.workflow_run.head_branch,github.event.workflow_run.display_title))[github.event_name == 'workflow_run'] }}

permissions:
  contents: read
  actions: read
  pull-requests: write
  checks: write
  issues: write

defaults:
  run:
    shell: powershell

env:
  workflowDepth: 1

jobs:
  Initialization:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: [ windows-latest ]
    outputs:
      output1: ${{ steps.step_prepare.outputs.PR_ENV }}

    steps:

      - id: step_prepare
        name: Display list information
        run: |
          $ErrorActionPreference = "STOP"
          Set-StrictMode -version 2.0
          $b = 'baba'
          echo "PR_ENV=$b" >> $env:GITHUB_OUTPUT

      - name: Create ticket
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Issue created due to workflow failure: ${{ github.run_id }}",
              body: "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n Step : **DELIVER** \n\n due to failure in run: _${{ github.run_id }}_. ${{ github.event.pull_request.head.repo.owner.login }}. context : " + context.sha,
              assignees: [ "jeelig" ],
              labels: [ "merge","deploy", "CICD" ]
            })
  Getter:
    needs: [ Initialization ]
    if: github.event.pull_request.merged == true
    steps:

      - id: getter_1
        name: Get info
        run: |
          echo "Hello World !"
          echo "Halla Warld !"

  Matrix:
    strategy: 
      matrix:
        include: [{"environment":"CORE_DEV (DEV)","os":"windows-latest"},{"environment":"CORE_QA (QA)","os":"windows-latest"}]
    runs-on: ${{matrix.os}}
    name: Deploy to ${{ matrix.environment }}
    steps:
      - name: Checkout
        run: echo "Hello world"



