# This is a basic workflow to help you get started with Actions

name: Test Branches

on: [workflow_dispatch]

jobs:
  build:
    name: 🚀 Test Branches
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE_BRANCH }}
          fetch-depth: 0

      - name: Command
        run: git branch --merged | grep -v "(^\*|master|main|dev)" | xargs git branch -d
